### ISSUE TITLE
`OCRC`: 2.1.0 Roadmap

### ISSUE THREAD

**Issue by pilgrimlyieu** [pilgrimlyieu/AutoHotkey-Script#24]
我对 OCRC 有了些新的想法，这意味着是时候做个规划了。

- [x] 自定义文本 OCR 引擎（目前无加入其它引擎的打算，但是应该做好准备）
  - [x] 默认配置
  - [x] 结果窗口
- [x] 自定义公式 OCR 引擎（免费的 Bing API 已经打包好了）
  - [x] 默认配置
  - [x] 结果窗口
- [x] 自定义百度 OCR 识别语言类型（目前仅支持中英文混合）
  - [x] 默认配置
  - [x] 结果窗口
- [x] 自定义百度 OCR 翻译类型（将输入和输出语言分离，全部自定义。这一点可能会导致选项冗杂，也许只应保留部分，剩余自行加入配置）
  - [x] 默认配置
  - [x] 结果窗口

> 由 GitHub Copilot 生成的翻译
> Generated by GitHub Copilot

I have some new ideas about OCRC, which means it's time to make a plan.

- [x] Custom text OCR engine (currently no plan to join other engines, but be prepared)
  - [x] Default setting
  - [x] Result Window
- [x] Custom formula OCR engine (the free Bing API has been packaged)
  - [x] Default setting
  - [x] Result Window
- [x] Custom Baidu OCR recognition language type (currently only supports Chinese and English mixed)
  - [x] Default setting
  - [x] Result Window
- [x] Custom Baidu OCR translation type (separate the input and output languages, all custom. This may cause the options to be redundant, perhaps only some should be retained, and the rest should be added to the configuration on user's own)
  - [x] Default setting
  - [x] Result Window
